import { lstat, mkdtemp, mkdir, readdir, rmdir, symlink, unlink } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { afterEach, beforeEach, expect, it } from 'vitest'
import { Media } from '../collections/Media'
import { createRevisionStorageCollection } from './revision-storage-binding'
import { readMediaRevision } from './revision-store'

let root = ''
let revisionRoot: string
let staticDir: string
beforeEach(async () => {
  root = ''
  root = await mkdtemp(path.join(tmpdir(), 'owner-revision-binding-'))
  revisionRoot = path.join(root, 'private')
  staticDir = path.join(root, 'native')
  await mkdir(revisionRoot)
  await mkdir(staticDir)
})
const ignoreMissing = async (action: () => Promise<unknown>) => {
  try { await action() } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
  }
}
afterEach(async () => {
  if (!root) return
  const link = path.join(root, 'link')
  await ignoreMissing(async () => {
    if (!(await lstat(link)).isSymbolicLink()) throw new Error('Expected the fixture junction')
    await unlink(link)
  })
  // Only these directories are created by this fixture. Nonempty directories
  // fail cleanup visibly; never traverse or remove unexpected contents.
  for (const directory of [path.join(root, 'native'), path.join(root, 'private'), root]) {
    await ignoreMissing(() => rmdir(directory))
  }
  root = ''
})

it.each(['absent', 'relative', 'missing', 'same', 'nested', 'filesystem-root'])('rejects %s storage settings before enabling uploads', async (fault) => {
  let settings = { revisionRoot, staticDir }
  if (fault === 'absent') settings = undefined as never
  if (fault === 'relative') settings.revisionRoot = 'private'
  if (fault === 'missing') settings.revisionRoot = path.join(root, 'missing')
  if (fault === 'same') settings.revisionRoot = staticDir
  if (fault === 'nested') settings.revisionRoot = root
  if (fault === 'filesystem-root') settings.revisionRoot = path.parse(root).root
  await expect(createRevisionStorageCollection(Media, settings)).rejects.toThrow()
})

it('rejects a linked root and leaves the supplied collection unchanged', async () => {
  const link = path.join(root, 'link')
  await symlink(revisionRoot, link, 'junction')
  await expect(createRevisionStorageCollection(Media, { revisionRoot: link, staticDir })).rejects.toThrow(/real directories/)
  const bound = await createRevisionStorageCollection(Media, { revisionRoot, staticDir })
  expect(typeof Media.upload === 'object' && Media.upload.disableLocalStorage).not.toBe(true)
  expect(bound.upload).toMatchObject({ disableLocalStorage: true, staticDir })
  expect(Media.fields.some((field) => 'name' in field && field.name === 'storageRevision')).toBe(false)
})

it('never falls through to native files and returns Responses for invalid and failed guarded reads', async () => {
  const bound = await createRevisionStorageCollection(Media, { revisionRoot, staticDir })
  const native = typeof bound.upload === 'object' && bound.upload.handlers?.[0]
  expect(native).toBeTruthy()
  const nativeResponse = await (native as Exclude<typeof native, false | undefined>)({} as never, {} as never)
  expect(nativeResponse).toBeInstanceOf(Response)
  expect(nativeResponse!.status).toBe(404)
  const endpoint = bound.endpoints && bound.endpoints.find((entry) => entry.path.startsWith('/revision/'))
  if (!endpoint) throw new Error('Missing revision endpoint')
  for (const req of [{}, { routeParams: { id: '1', revision: '11111111-1111-4111-8111-111111111111', filename: 'image.png' } }]) {
    const response = await endpoint.handler(req as never)
    expect(response).toBeInstanceOf(Response)
    expect(response.status).toBe(404)
  }
})

it('stores one complete file when Payload aliases identical generated bytes to the original filename', async () => {
  const bound = await createRevisionStorageCollection(Media, { revisionRoot, staticDir })
  const hook = bound.hooks?.beforeChange?.at(-1)
  if (!hook) throw new Error('Missing revision beforeChange hook')
  const bytes = Buffer.from('complete-image-bytes')
  const data = await hook({
    data: { filename: 'image.png', sizes: { large: { filename: 'image.png' } } },
    originalDoc: undefined,
    req: { file: { data: bytes }, payloadUploadSizes: { large: Buffer.from(bytes) } },
  } as never)
  const revision = data.storageRevision as string
  expect(await readMediaRevision(revisionRoot, revision)).toEqual([{ name: 'image.png', bytes }])
  await unlink(path.join(revisionRoot, revision, 'image.png'))
  await unlink(path.join(revisionRoot, revision, 'manifest.json'))
  await rmdir(path.join(revisionRoot, revision))
})

it('rejects conflicting generated bytes for one filename without creating a revision', async () => {
  const bound = await createRevisionStorageCollection(Media, { revisionRoot, staticDir })
  const hook = bound.hooks?.beforeChange?.at(-1)
  if (!hook) throw new Error('Missing revision beforeChange hook')
  const before = await readdir(revisionRoot)
  await expect(hook({
    data: { filename: 'image.png', sizes: { large: { filename: 'image.png' } } },
    originalDoc: undefined,
    req: { file: { data: Buffer.from('original') }, payloadUploadSizes: { large: Buffer.from('conflict') } },
  } as never)).rejects.toThrow(/conflicting bytes/)
  expect(await readdir(revisionRoot)).toEqual(before)
})

it.each([
  'http://media.example.com:444',
  'http://127.0.0.1',
  'https://media.example.com/',
  'https://media.example.com/path',
  'https://media.example.com?query=1',
  'https://media.example.com#hash',
  'https://user:secret@media.example.com',
  'ftp://media.example.com',
])('rejects noncanonical or insecure native fetch origin %s', async (nativeFetchOrigin) => {
  await expect(createRevisionStorageCollection(Media, { nativeFetchOrigin, revisionRoot, staticDir })).rejects.toThrow(/origin/)
})

it.each(['https://media.example.com', 'http://127.0.0.1:43210'])('accepts explicit canonical native fetch origin %s', async (nativeFetchOrigin) => {
  const bound = await createRevisionStorageCollection(Media, { nativeFetchOrigin, revisionRoot, staticDir })
  expect(bound.slug).toBe('media')
})

it('fails native crop and duplication closed without a configured origin', async () => {
  const bound = await createRevisionStorageCollection(Media, { revisionRoot, staticDir })
  const hook = bound.hooks?.beforeOperation?.at(-1)
  if (!hook) throw new Error('Missing revision beforeOperation hook')
  const req = { headers: new Headers({ Origin: 'https://media.example.com' }), query: {}, user: { collection: 'users', id: 1, role: 'owner' } }
  await expect(hook({ operation: 'create', args: { data: {}, duplicateFromID: 42 }, req } as never))
    .rejects.toMatchObject({ status: 403 })
  await expect(hook({ operation: 'update', args: { data: { focalX: 40 }, id: 42 }, req } as never))
    .rejects.toMatchObject({ status: 403 })
})

it('builds duplicate refetch URLs only from the server operation capability', async () => {
  const nativeFetchOrigin = 'https://media.example.com'
  const bound = await createRevisionStorageCollection(Media, { nativeFetchOrigin, revisionRoot, staticDir })
  const operationHook = bound.hooks?.beforeOperation?.at(-1)
  const urlField = bound.fields.find((field) => 'name' in field && field.name === 'url')
  const urlHook = urlField && 'hooks' in urlField && urlField.hooks?.afterRead?.at(-1)
  if (!operationHook || !urlHook) throw new Error('Missing native duplication hooks')
  const req = {
    headers: new Headers({ Origin: nativeFetchOrigin }), payload: { config: { routes: { api: '/api' } } }, query: {},
    user: { collection: 'users', id: 1, role: 'owner' },
  }
  await operationHook({ operation: 'create', args: { data: { url: 'https://attacker.invalid/file.png' }, duplicateFromID: 42 }, req } as never)
  const revision = '11111111-1111-4111-8111-111111111111'
  expect(await urlHook({ originalDoc: { filename: 'source.png', storageRevision: revision }, req, value: 'https://attacker.invalid/file.png' } as never))
    .toBe(`/api/media/revision/42/${revision}/source.png`)
})
