/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'media-placements': MediaPlacement;
    'brand-profiles': BrandProfile;
    projects: Project;
    articles: Article;
    pages: Page;
    'preview-snapshots': PreviewSnapshot;
    releases: Release;
    'audit-events': AuditEvent;
    'assistance-proposals': AssistanceProposal;
    'restore-plans': RestorePlan;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'media-placements': MediaPlacementsSelect<false> | MediaPlacementsSelect<true>;
    'brand-profiles': BrandProfilesSelect<false> | BrandProfilesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'preview-snapshots': PreviewSnapshotsSelect<false> | PreviewSnapshotsSelect<true>;
    releases: ReleasesSelect<false> | ReleasesSelect<true>;
    'audit-events': AuditEventsSelect<false> | AuditEventsSelect<true>;
    'assistance-proposals': AssistanceProposalsSelect<false> | AssistanceProposalsSelect<true>;
    'restore-plans': RestorePlansSelect<false> | RestorePlansSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'assistant-settings': AssistantSetting;
  };
  globalsSelect: {
    'assistant-settings': AssistantSettingsSelect<false> | AssistantSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'owner';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-placements".
 */
export interface MediaPlacement {
  id: number;
  name: string;
  placement: {
    asset: number | Media;
    focalX: number;
    focalY: number;
    zoom: number;
    fit: 'cover' | 'contain';
    frame: 'auto' | '16:9' | '4:3' | '1:1' | '9:16';
    overrides?: {
      mobile?: {
        focalX?: number | null;
        focalY?: number | null;
        zoom?: number | null;
        fit?: ('cover' | 'contain') | null;
        frame?: ('auto' | '16:9' | '4:3' | '1:1' | '9:16') | null;
      };
      tablet?: {
        focalX?: number | null;
        focalY?: number | null;
        zoom?: number | null;
        fit?: ('cover' | 'contain') | null;
        frame?: ('auto' | '16:9' | '4:3' | '1:1' | '9:16') | null;
      };
    };
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-profiles".
 */
export interface BrandProfile {
  id: number;
  _order?: string | null;
  name: string;
  slug: string;
  /**
   * Roles semánticos. Se validan completamente al publicar.
   */
  colors?:
    | {
        role: 'background' | 'surface' | 'text' | 'mutedText' | 'accent' | 'interaction' | 'success' | 'danger';
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Objetivos compositivos; deben sumar 100 al publicar.
   */
  usageWeights?:
    | {
        role: 'background' | 'surface' | 'text' | 'mutedText' | 'accent' | 'interaction' | 'success' | 'danger';
        weight: number;
        id?: string | null;
      }[]
    | null;
  typography?: {
    primaryFamily?: string | null;
    secondaryFamily?: string | null;
    fontAssets?: (number | Media)[] | null;
  };
  assets?: {
    logos?: (number | Media)[] | null;
    images?: (number | Media)[] | null;
    icons?: (number | Media)[] | null;
  };
  voiceNotes?: string | null;
  motion?: {
    duration?: number | null;
    stagger?: number | null;
    travel?: number | null;
    easing?: ('linear' | 'ease' | 'ease-in' | 'ease-out' | 'ease-in-out') | null;
    reducedMotion?: ('reduce' | 'disable') | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  _order?: string | null;
  title: string;
  slug: string;
  summary: string;
  heroImage: number | Media;
  /**
   * Encuadre no destructivo opcional para la imagen principal.
   */
  heroPlacement?: (number | null) | MediaPlacement;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  technologies?:
    | {
        name: string;
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  year?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  coverImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  _order?: string | null;
  title: string;
  slug: string;
  /**
   * Obligatorio al publicar. Los borradores pueden guardarse sin asignarlo.
   */
  brandProfile?: (number | null) | BrandProfile;
  /**
   * Variaciones controladas; fondo y texto siempre se heredan.
   */
  brandOverrides?: {
    accent?: string | null;
    surface?: string | null;
    usageWeights?:
      | {
          role: 'background' | 'surface' | 'text' | 'mutedText' | 'accent' | 'interaction' | 'success' | 'danger';
          weight: number;
          id?: string | null;
        }[]
      | null;
    motion?: {
      duration?: number | null;
      stagger?: number | null;
      travel?: number | null;
      easing?: ('linear' | 'ease' | 'ease-in' | 'ease-out' | 'ease-in-out') | null;
      reducedMotion?: ('reduce' | 'disable') | null;
    };
  };
  layout: (
    | {
        eyebrow?: string | null;
        heading: string;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        image?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        heading?: string | null;
        projects?: (number | Project)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'projectGrid';
      }
    | {
        asset: number | Media;
        /**
         * Encuadre reutilizable opcional; nunca modifica el original.
         */
        placement?: (number | null) | MediaPlacement;
        caption?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'media';
      }
    | {
        featureKey: 'project-reel' | 'research-index' | 'contact-panel';
        heading?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'customFeature';
      }
  )[];
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "preview-snapshots".
 */
export interface PreviewSnapshot {
  id: number;
  schemaVersion: number;
  sourceCollection: string;
  sourceDocumentId: string;
  sourceVersionId: string;
  manifest:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  manifestHash: string;
  createdBy: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "releases".
 */
export interface Release {
  id: number;
  name: string;
  changeSummary: string;
  gitCommit: string;
  previewSnapshot: number | PreviewSnapshot;
  quality: {
    viewport: 'desktop' | 'mobile';
    performance: number;
    usability: number;
    accessibility: number;
    source: 'lighthouse' | 'manual';
    measuredAt: string;
    id?: string | null;
  }[];
  createdBy: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events".
 */
export interface AuditEvent {
  id: number;
  actor: number | User;
  action: string;
  subjectCollection: string;
  subjectId: string;
  outcome: 'success' | 'denied' | 'failure';
  metadata:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assistance-proposals".
 */
export interface AssistanceProposal {
  id: number;
  targetPage: number | Page;
  sourceSnapshot: number | PreviewSnapshot;
  capability: 'suggestCopy' | 'suggestPalette' | 'suggestLayout' | 'suggestCrop' | 'suggestMotion';
  provider: string;
  patch:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'pending' | 'accepted' | 'rejected';
  createdBy: number | User;
  decisionNote?: string | null;
  decidedBy?: (number | null) | User;
  decidedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "restore-plans".
 */
export interface RestorePlan {
  id: number;
  release: number | Release;
  targetPage: number | Page;
  targetSnapshot: number | PreviewSnapshot;
  targetHash: string;
  baselineSnapshot: number | PreviewSnapshot;
  baselineHash: string;
  status: 'ready' | 'confirmed' | 'conflict';
  createdBy: number | User;
  confirmationSnapshot?: (number | null) | PreviewSnapshot;
  conflictHash?: string | null;
  confirmedBy?: (number | null) | User;
  confirmedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'media-placements';
        value: number | MediaPlacement;
      } | null)
    | ({
        relationTo: 'brand-profiles';
        value: number | BrandProfile;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'preview-snapshots';
        value: number | PreviewSnapshot;
      } | null)
    | ({
        relationTo: 'releases';
        value: number | Release;
      } | null)
    | ({
        relationTo: 'audit-events';
        value: number | AuditEvent;
      } | null)
    | ({
        relationTo: 'assistance-proposals';
        value: number | AssistanceProposal;
      } | null)
    | ({
        relationTo: 'restore-plans';
        value: number | RestorePlan;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-placements_select".
 */
export interface MediaPlacementsSelect<T extends boolean = true> {
  name?: T;
  placement?:
    | T
    | {
        asset?: T;
        focalX?: T;
        focalY?: T;
        zoom?: T;
        fit?: T;
        frame?: T;
        overrides?:
          | T
          | {
              mobile?:
                | T
                | {
                    focalX?: T;
                    focalY?: T;
                    zoom?: T;
                    fit?: T;
                    frame?: T;
                  };
              tablet?:
                | T
                | {
                    focalX?: T;
                    focalY?: T;
                    zoom?: T;
                    fit?: T;
                    frame?: T;
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-profiles_select".
 */
export interface BrandProfilesSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  slug?: T;
  colors?:
    | T
    | {
        role?: T;
        value?: T;
        id?: T;
      };
  usageWeights?:
    | T
    | {
        role?: T;
        weight?: T;
        id?: T;
      };
  typography?:
    | T
    | {
        primaryFamily?: T;
        secondaryFamily?: T;
        fontAssets?: T;
      };
  assets?:
    | T
    | {
        logos?: T;
        images?: T;
        icons?: T;
      };
  voiceNotes?: T;
  motion?:
    | T
    | {
        duration?: T;
        stagger?: T;
        travel?: T;
        easing?: T;
        reducedMotion?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  summary?: T;
  heroImage?: T;
  heroPlacement?: T;
  body?: T;
  technologies?:
    | T
    | {
        name?: T;
        icon?: T;
        id?: T;
      };
  year?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  content?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  brandProfile?: T;
  brandOverrides?:
    | T
    | {
        accent?: T;
        surface?: T;
        usageWeights?:
          | T
          | {
              role?: T;
              weight?: T;
              id?: T;
            };
        motion?:
          | T
          | {
              duration?: T;
              stagger?: T;
              travel?: T;
              easing?: T;
              reducedMotion?: T;
            };
      };
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        projectGrid?:
          | T
          | {
              heading?: T;
              projects?: T;
              id?: T;
              blockName?: T;
            };
        media?:
          | T
          | {
              asset?: T;
              placement?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        customFeature?:
          | T
          | {
              featureKey?: T;
              heading?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "preview-snapshots_select".
 */
export interface PreviewSnapshotsSelect<T extends boolean = true> {
  schemaVersion?: T;
  sourceCollection?: T;
  sourceDocumentId?: T;
  sourceVersionId?: T;
  manifest?: T;
  manifestHash?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "releases_select".
 */
export interface ReleasesSelect<T extends boolean = true> {
  name?: T;
  changeSummary?: T;
  gitCommit?: T;
  previewSnapshot?: T;
  quality?:
    | T
    | {
        viewport?: T;
        performance?: T;
        usability?: T;
        accessibility?: T;
        source?: T;
        measuredAt?: T;
        id?: T;
      };
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events_select".
 */
export interface AuditEventsSelect<T extends boolean = true> {
  actor?: T;
  action?: T;
  subjectCollection?: T;
  subjectId?: T;
  outcome?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assistance-proposals_select".
 */
export interface AssistanceProposalsSelect<T extends boolean = true> {
  targetPage?: T;
  sourceSnapshot?: T;
  capability?: T;
  provider?: T;
  patch?: T;
  status?: T;
  createdBy?: T;
  decisionNote?: T;
  decidedBy?: T;
  decidedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "restore-plans_select".
 */
export interface RestorePlansSelect<T extends boolean = true> {
  release?: T;
  targetPage?: T;
  targetSnapshot?: T;
  targetHash?: T;
  baselineSnapshot?: T;
  baselineHash?: T;
  status?: T;
  createdBy?: T;
  confirmationSnapshot?: T;
  conflictHash?: T;
  confirmedBy?: T;
  confirmedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Permisos para generar propuestas. Aplicar, publicar y desplegar nunca se conceden al asistente.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assistant-settings".
 */
export interface AssistantSetting {
  id: number;
  suggestCopy?: boolean | null;
  suggestPalette?: boolean | null;
  suggestLayout?: boolean | null;
  suggestCrop?: boolean | null;
  suggestMotion?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assistant-settings_select".
 */
export interface AssistantSettingsSelect<T extends boolean = true> {
  suggestCopy?: T;
  suggestPalette?: T;
  suggestLayout?: T;
  suggestCrop?: T;
  suggestMotion?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}